name: 'Deploy Docker Images'
description: 'Deploy Docker images using Docker Compose and run smoke tests'
inputs:
  environment:
    description: 'Target deployment environment (e.g., qa, staging, production)'
    required: true
  version:
    description: 'Release version to deploy (e.g., v1.0.4-rc)'
    required: true
  image-urls:
    description: 'Docker image URLs to deploy (JSON array format)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone Base Repository
      run: |
        echo "📥 Cloning base repository..."
        git clone https://github.com/optivem/modern-acceptance-testing-in-legacy-code.git modern-acceptance-testing-in-legacy-code
        echo "✅ Base repository cloned successfully"
      shell: bash

    - name: Deploy System
      run: |
        echo "🚀 Deploying system version ${{ inputs.version }} to ${{ inputs.environment }} environment..."
        echo ""
        
        # List Docker images being deployed
        if [[ -n "${{ inputs.image-urls }}" ]]; then
          echo "📦 Deploying the following Docker images:"
          
          # Parse JSON array and iterate through each URL
          echo '${{ inputs.image-urls }}' | jq -r '.[]' | while IFS= read -r image_url; do
            if [[ -n "$image_url" ]]; then
              echo "   🐳 Deploying: $image_url"
            fi
          done
          echo ""
        fi
        
        echo "📝 Note: We are simulating deployment using Docker Compose Up for testing purposes."
        echo "🏭 In real applications, this is where you would deploy to:"
        echo "   - AWS (ECS, EKS, Lambda, EC2)"
        echo "   - Azure (Container Instances, AKS, App Service)"
        echo "   - GCP (Cloud Run, GKE, Compute Engine)"
        echo "   - On-premise (Kubernetes, Docker Swarm, VMs)"
        echo "   - Other cloud providers (DigitalOcean, Linode, etc.)"
        echo ""
        echo "🐳 Starting Docker Compose for simulated deployment..."
        docker compose -f modern-acceptance-testing-in-legacy-code/docker-compose.pipeline.yml up -d
      shell: bash

    - name: Wait for System - Frontend
      uses: optivem/wait-for-docker-compose-action@v1
      with:
        url: 'http://localhost:3001/'
        max-attempts: '30'
        wait-seconds: '10'

    - name: Wait for System - Backend
      uses: optivem/wait-for-docker-compose-action@v1
      with:
        url: 'http://localhost:8081/health'
        max-attempts: '30'
        wait-seconds: '10'

    - name: Wait for System - ERP
      uses: optivem/wait-for-docker-compose-action@v1
      with:
        url: 'http://localhost:9001/erp/health'
        max-attempts: '30'
        wait-seconds: '10'

    - name: Wait for System - Tax
      uses: optivem/wait-for-docker-compose-action@v1
      with:
        url: 'http://localhost:9001/tax/health'
        max-attempts: '30'
        wait-seconds: '10'
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      shell: bash
    
    - name: Build Workspace Packages
      run: |
        cd optivem-results && npm run build && cd ..
        cd optivem-lang && npm run build && cd ..
        cd optivem-http && npm run build && cd ..
        cd optivem-playwright && npm run build && cd ..
        cd optivem-testing-channels && npm run build && cd ..
        cd optivem-testing-assertions && npm run build && cd ..
      shell: bash
    
    - name: Install Playwright Browsers
      run: npx playwright install
      shell: bash
      working-directory: system-test
        
    - name: Run Smoke Tests
      run: npm test -- tests/smoke-tests
      shell: bash
      working-directory: system-test